version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: zigbee2mqtt_server_1
      APP_PORT: 8080

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - ./data:/app/data:rw
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Asia/Yekaterinburg
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D99113-if00:/dev/ttyACM0
    init: true
  
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - 1883:1883 #default mqtt port
      - 9001:9001 #default mqtt port for websockets
    volumes:
      - ./data/mqtt/config:/mosquitto/config:rw
      - ./data/mqtt/:/mosquitto/data:rw
      - ./data/mqtt/log:/mosquitto/log:rw
    restart: always
